# Use postgres/example user/password credentials
version: '3.1'

services:

  app:
    container_name: "ok-scoring-py-app"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - ok-scoring-db
    env_file: docker-compose.env
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "5005:80"

  ok-scoring-db:
    container_name: "ok-scoring-py-db"
    image: postgres
    restart: always
    env_file: docker-compose.env
    volumes:
      - ok-scoring-data:/var/lib/postgresql
    ports:
      - 5432:5432

volumes:
  ok-scoring-data: