"""Add ordering for score round

Revision ID: 6107df5494b8
Revises: 283dc05166fc
Create Date: 2021-09-13 23:44:45.806474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6107df5494b8'
down_revision = '283dc05166fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scoreRound', sa.Column('order', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scoreRound', 'order')
    # ### end Alembic commands ###
