"""Adding order prop to player score history

Revision ID: 91ebeccc981a
Revises: 6b96d80d8d23
Create Date: 2021-05-31 22:39:13.618335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91ebeccc981a'
down_revision = '6b96d80d8d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerScoreHistory', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playerScoreHistory', 'order')
    # ### end Alembic commands ###
