"""remove gam rules v1

Revision ID: 981913de8599
Revises: 6107df5494b8
Create Date: 2021-11-21 08:49:13.955498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '981913de8599'
down_revision = '6107df5494b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gameRules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameRules',
    sa.Column('key', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('gameKey', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('startingScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('scoreIncreasesByDefault', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('defaultScoreStep', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minRoundsToWin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maxRounds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minRoundScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maxRoundScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('minPlayers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('maxPlayers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('winningScore', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('canBust', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('highScoreWins', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('setScores', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gameKey'], ['game.key'], name='gameRules_gameKey_fkey'),
    sa.PrimaryKeyConstraint('key', name='gameRules_pkey')
    )
    # ### end Alembic commands ###
