"""Renaming rules v2 to rules

Revision ID: 9efb9a3ac02d
Revises: 981913de8599
Create Date: 2021-11-21 08:52:23.858007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9efb9a3ac02d'
down_revision = '981913de8599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameRules',
    sa.Column('key', postgresql.UUID(), nullable=False),
    sa.Column('gameKey', postgresql.UUID(), nullable=True),
    sa.Column('validStateSchema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('winningSchema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('firstToScoreWins', sa.Boolean(), nullable=True),
    sa.Column('scoreIncreasesByDefault', sa.Boolean(), nullable=True),
    sa.Column('highScoreWins', sa.Boolean(), nullable=True),
    sa.Column('playersMustBeOnSameRound', sa.Boolean(), nullable=True),
    sa.Column('dealerSettings', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['gameKey'], ['game.key'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_table('gameRulesV2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gameRulesV2',
    sa.Column('key', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('gameKey', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('validStateSchema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('winningSchema', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('firstToScoreWins', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('scoreIncreasesByDefault', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('highScoreWins', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('playersMustBeOnSameRound', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('dealerSettings', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['gameKey'], ['game.key'], name='gameRulesV2_gameKey_fkey'),
    sa.PrimaryKeyConstraint('key', name='gameRulesV2_pkey')
    )
    op.drop_table('gameRules')
    # ### end Alembic commands ###
